[package]
name = "webdeploy"
version = "0.1.0"
edition = "2024"

[dependencies]
awesome_axum_responses = { git = "https://github.com/DragonFoxCollective/awesome_axum_responses.git", features = [
  "anyhow"
] }
axum = "0.8.9"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"

[features]
default = []
always-build = []
